name: CI/CD
on:
  push:
    branches:
      - master
      - production

jobs:
  deploy_alpha:
    name: Deploy - Alpha
    runs-on: ubuntu-latest
    environment:
      name: deployment
      url: https://sourctom/${{ matrix.theme }}/
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        theme: ['no', 'yes']
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

  deploy_prod:
    name: Deploy - Production
    runs-on: ubuntu-latest
    environment:
      name: deployment
      url: https://sourad-onom/${{ matrix.theme }}/
    if: github.ref == 'refs/heads/production'
    strategy:
      matrix:
        theme: ['intl', 'vig']
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

