name: CI/CD
on:
  push:
    branches:
      - master
      - production

jobs:
  alpha:
    name: alpha
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        theme: ['int', 'test 1']
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5


  prod:
    name: prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    strategy:
      matrix:
        theme: ['in', 'foo']
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
