name: Deploy to Amazon ECS
on:
  push:
    branches:
      - master
env:
  AWS_REGION: us-east-3
  ECS_CLUSTER: app_cluster
  CONTAINER_NAME: app
  ECS_SERVICE: app_service

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: sentry-cli
        uses: getsentry/action-release@v3
        with:
          environment: dev
          org: sentry-org
          release: 1.2.3